### ISSUE TITLE
Validation error and the json parser isn't properly pulling the error while initialise T1 with json=True.

### ISSUE THREAD

**Issue by sujitkn** [MediaMath/t1-python#102]
t1 = T1(auth_method='cookie', session_id='d3c001d9562d42660f6fa65897e5a32fc0786c9d', json=True, api_base='api.mediamath.com')

>>> strategy_props = {
...         "budget": 10.00,
...         "campaign_id": "297601",
...         "frequency_type": "even",
...         "goal_type": 'spend',
...         "goal_value": 10.00,
...         "max_bid": 10,
...         "name": "Training Demo Demo1",
...         "pacing_amount": 1,
...         "type": "GBO",
...         "status": 1,
...         "use_campaign_start": 1,
...         "use_campaign_end": 1,
...     "impression_pacing_interval":'hour',
...     "frequency_amount":1,
...     "frequency_interval":"hour"
...     }
>>> st=t1.new("strategy", properties=strategy_props)
>>> st.save()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\terminalone\models\strategy.py", line 265, in save
    super(Strategy, self).save(data=data, url=url)
  File "C:\Python27\lib\site-packages\terminalone\entity.py", line 196, in save
    entity, _ = super(Entity, self)._post(PATHS['mgmt'], url, data=data)
  File "C:\Python27\lib\site-packages\terminalone\connection.py", line 205, in _post
    return self._parse_response(response)
  File "C:\Python27\lib\site-packages\terminalone\connection.py", line 214, in _parse_response
    result = self._parser(response_body)
  File "C:\Python27\lib\site-packages\terminalone\jsonparser.py", line 45, in __init__
    self.get_status(parsed_data, body)
  File "C:\Python27\lib\site-packages\terminalone\jsonparser.py", line 90, in get_status
    message = self._parse_field_error(data)
  File "C:\Python27\lib\site-packages\terminalone\jsonparser.py", line 137, in _parse_field_error
    errors[error['field']] = {'code': error['field-error'],
KeyError: 'field-error'
>>>

**Comment by pswaminathan** [comment]
This was fixed in #106
